// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/apigateway/api-gw-execution-logging-enabled": {
            "get": {
                "description": "Checks if logging is enabled for all stages of API Gateway REST or WebSocket APIs.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "APIGateway"
                ],
                "summary": "Checks if logging is enabled for all stages of API Gateway REST or WebSocket APIs.",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/ecs/ecs-task-definition-user-for-host-mode-check": {
            "get": {
                "description": "Checks for secure networking modes and user definitions in ECS task definitions.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ECS"
                ],
                "summary": "Checks for secure networking modes and user definitions in ECS task definitions.",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/srv/hello": {
            "get": {
                "description": "Server Health Check",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server Utils"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
