info:
  contact: {}
paths:
  /ecs/ecs-task-definition-user-for-host-mode-check:
    get:
      description: Checks for secure networking modes and user definitions in ECS
        task definitions.
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Checks for secure networking modes and user definitions in ECS task
        definitions.
      tags:
      - ECS
  /srv/hello:
    get:
      consumes:
      - application/json
      description: Server Health Check
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Health Check
      tags:
      - Server Utils
swagger: "2.0"
